first draft
original4sure/markapp pull request #1
Opened 2023-07-13 06:46 UTC by sachinnagpal

2023-07-15 04:20 UTC, riturajborpujari requested changes

2023-07-15 04:20 UTC, riturajborpujari commented on src/ui/script.js
> +        if (isSuccessfullyStopped) {
use this naming convention for boolean variables like `isUpdatedSuccessfully` above

2023-07-15 04:20 UTC, riturajborpujari commented on src/ui/script.js
> +      let updatedSuccesfully = status['updated-successfully']
Use name `isUpdatedSuccessfully`

2023-07-15 04:20 UTC, riturajborpujari commented on src/ui/script.js
> +  if (serviceStatuses.length > 0 && serviceStatuses.length < 7) {
Why is this `< 7 ` check required?

if this has a required logic behind, extract away into its method and give a relevant name

2023-07-15 04:20 UTC, riturajborpujari commented on src/ui/script.js
> +  } else if (serviceStatuses.length === 7) {
Same comment as above.

Extract out into something like `areAllServiceRunning` if required

2023-07-15 04:20 UTC, riturajborpujari commented on src/ui/script.js
> +    else if (installationStatus.servicesNotRunning.length > 0) {
if status fields `listedServicesRunning`, `startingServices`, and `servicesDownloaded` are mutually exclusive, they should be the possible values of a single `serviceStatus` field

```ts
export type serviceStatus: "listedServicesRunning" | "startingServices" | "servicesDownloaded"
```

2023-07-18 09:15 UTC, sachinnagpal commented on src/backend/update.js
> +    stopServicesAndAlert()
Moved it to a new service file itself.

2023-07-18 09:17 UTC, sachinnagpal commented on src/backend/update.js
> +      'installation-successful': false
For installer case we have that, but for update not doing it currently. Can bring it up in next phase

2023-07-18 09:18 UTC, sachinnagpal commented on src/ui/script.js
> +  if (serviceStatuses.length > 0 && serviceStatuses.length < 7) {
Will try to simplify this complete logic in next phase. Will discuss it with @shailendraO4S as well to right it in more cleaner way.

2023-07-20 06:03 UTC, riturajborpujari approved these changes

2023-07-20 06:04 UTC, sachinnagpal commented
There are few comments which need to be resolved in phase 2. Mostly from front end and one related to init method in backend. 
cc: @riturajborpujari

2023-07-20 07:28 UTC, merged